server {
    listen 80;

    location / {
        proxy_pass http://frontend:8000;
    }

    location /test_rds/ {
        proxy_pass http://backend-rds:8000/test_connection/;
    }

    location /test_redis/ {
        proxy_pass http://backend-redis:8000/test_connection/;
    }
}